#!/usr/bin/env bash
# No service interruption

PID=$(pgrep -f gunicorn)

if [ -n "$PID" ]; then
    # Send HUP signal to the Gunicorn master process to reload it gracefully
    kill -HUP "$PID"
    echo "Gunicorn reloaded successfully (PID: $PID)."
else
    echo "Gunicorn is not running."
fi
